CREATE TABLE IF NOT EXISTS smeta_grafik_old (
    id SERIAL PRIMARY KEY,
    smeta_id INTEGER REFERENCES smeta(id),
    spravochnik_budjet_name_id INTEGER REFERENCES spravochnik_budjet_name(id),
    main_schet_id INTEGER REFERENCES main_schet(id) NOT NULL,
    sort_order INTEGER NOT NULL,
    itogo DECIMAL DEFAULT 0,
    oy_1 DECIMAL DEFAULT 0,
    oy_2 DECIMAL DEFAULT 0,
    oy_3 DECIMAL DEFAULT 0,
    oy_4 DECIMAL DEFAULT 0,
    oy_5 DECIMAL DEFAULT 0,
    oy_6 DECIMAL DEFAULT 0,
    oy_7 DECIMAL DEFAULT 0,
    oy_8 DECIMAL DEFAULT 0,
    oy_9 DECIMAL DEFAULT 0,
    oy_10 DECIMAL DEFAULT 0,
    oy_11 DECIMAL DEFAULT 0,
    oy_12 DECIMAL DEFAULT 0,
    year INT NOT NULL,
    user_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    isdeleted BOOLEAN DEFAULT FALSE
);