exports.CODE = {
  DOCS_HAVE: {
    code: 1001,
  },
  OK: {
    code: 1000,
  },
  SALDO_CREATE: {
    code: 1002,
  },
  EXCEL_IMPORT: {
    code: 1003,
  },
};

exports.REPORT_RASXOD_SCHET = ["231", "261"];

exports.REPORT_TYPE = {
  cap: "cap",
  days_report: "daysReport",
};

exports.JURNAL_SCHETS = ["jur1_schet", "jur2_schet"];

exports.SALDO_PASSWORD = "smart-base-e-moliya-fvv";

exports.LIMIT = 999999999999999;

exports.PAGE = 1;

exports.SCHET_TYPE = ["work_trip", "bank_rasxod", "bank_prixod", "kassa_prixod", "kassa_rasxod", "avans_otchet"];

exports.REPORT_TITLE = "Меморалний ордер";

exports.REGIONS = [
  {
    id: 101,
    title: "Qoraqalpog‘iston",
    "hc-key": "uz-qr",
    districts: [
      {
        id: 1010,
        regionId: 101,
        title: { latin: "Nukus", cyrl: "Нукус шаҳар", en: "Nukus district" },
        phoneKod: "0",
        cOrder: "1",
        ns11Code: "1",
        soato: "1735401",
      },
      {
        id: 1001,
        regionId: 101,
        title: {
          latin: "Amudaryo tumani",
          cyrl: "Амударё тумани",
          en: "Amudaryo district",
        },
        phoneKod: "0",
        cOrder: "2",
        ns11Code: "8",
        soato: "1735204",
      },
      {
        id: 1002,
        regionId: 101,
        title: {
          latin: "Beruniy tumani",
          cyrl: "Беруний тумани",
          en: "Beruniy district",
        },
        phoneKod: "0",
        cOrder: "3",
        ns11Code: "9",
        soato: "1735207",
      },
      {
        id: 1005,
        regionId: 101,
        title: {
          latin: "Qanliko‘l tumani",
          cyrl: "Қонликўл тумани",
          en: "Kanlikul district",
        },
        phoneKod: "0",
        cOrder: "4",
        ns11Code: "13",
        soato: "1735218",
      },
      {
        id: 1006,
        regionId: 101,
        title: {
          latin: "Qorao‘zak tumani",
          cyrl: "Қораўзак тумани",
          en: "Karaosak district",
        },
        phoneKod: "0",
        cOrder: "5",
        ns11Code: "22",
        soato: "1735211",
      },
      {
        id: 1508,
        regionId: 1,
        title: {
          latin: "Bo‘zatov tumani",
          cyrl: "Бўзатов тумани",
          en: "Bo‘zatov district",
        },
        phoneKod: "0",
        cOrder: "8",
        ns11Code: "13",
        soato: "1735214",
      },
      {
        id: 1004,
        regionId: 101,
        title: {
          latin: "Kegeyli tumani",
          cyrl: "Кегейли тумани",
          en: "Kegeyli district",
        },
        phoneKod: "0",
        cOrder: "6",
        ns11Code: "11",
        soato: "1735212",
      },
      {
        id: 1007,
        regionId: 101,
        title: {
          latin: "Qo‘ng‘irot tumani",
          cyrl: "Қўнғирот тумани",
          en: "Kungrad district",
        },
        phoneKod: "0",
        cOrder: "7",
        ns11Code: "12",
        soato: "1735215",
      },
      {
        id: 1008,
        regionId: 101,
        title: {
          latin: "Mo‘ynoq tumani",
          cyrl: "Муйноқ тумани",
          en: "Muynak district",
        },
        phoneKod: "0",
        cOrder: "8",
        ns11Code: "14",
        soato: "1735222",
      },
      {
        id: 1009,
        regionId: 101,
        title: {
          latin: "Nukus tumani",
          cyrl: "Нукус тумани",
          en: "Nukus district",
        },
        phoneKod: "0",
        cOrder: "9",
        ns11Code: "15",
        soato: "1735225",
      },
      {
        id: 1012,
        regionId: 101,
        title: {
          latin: "Taxtako‘pir tumani",
          cyrl: "Тахтакўприк тумани",
          en: "Tahtakuprik district",
        },
        phoneKod: "0",
        cOrder: "10",
        ns11Code: "16",
        soato: "1735230",
      },
      {
        id: 1013,
        regionId: 101,
        title: {
          latin: "To‘rtko‘l tumani",
          cyrl: "Тўрткўл тумани",
          en: "Turtkul district",
        },
        phoneKod: "0",
        cOrder: "11",
        ns11Code: "17",
        soato: "1735233",
      },
      {
        id: 1014,
        regionId: 101,
        title: {
          latin: "Xo‘jayli tumani",
          cyrl: "Хўжайли тумани",
          en: "Khodzhayli district",
        },
        phoneKod: "0",
        cOrder: "12",
        ns11Code: "18",
        soato: "1735236",
      },
      {
        id: 1015,
        regionId: 101,
        title: {
          latin: "Chimboy tumani",
          cyrl: "Чимбой тумани",
          en: "Chimbay district",
        },
        phoneKod: "0",
        cOrder: "13",
        ns11Code: "19",
        soato: "1735240",
      },
      {
        id: 1016,
        regionId: 101,
        title: {
          latin: "Shumanay tumani",
          cyrl: "Шўманай тумани",
          en: "Shumanay district",
        },
        phoneKod: "0",
        cOrder: "14",
        ns11Code: "20",
        soato: "1735243",
      },
      {
        id: 1017,
        regionId: 101,
        title: {
          latin: "Ellikqala tumani",
          cyrl: "Элликқалъа тумани",
          en: "Ellikqal'a district",
        },
        phoneKod: "0",
        cOrder: "15",
        ns11Code: "21",
        soato: "1735250",
      },
      {
        id: 1011,
        regionId: 101,
        title: {
          latin: "Taxiatosh tumani",
          cyrl: " Тахиатош тумани",
          en: "Taxiatosh district",
        },
        phoneKod: "0",
        cOrder: "16",
        ns11Code: "2019",
        soato: "1735228",
      },
    ],
  },
  {
    id: 103,
    title: "Buxoro viloyati",
    "hc-key": "uz-bu",
    districts: [
      {
        id: 1038,
        regionId: 103,
        title: {
          latin: "Buxoro shahar",
          cyrl: "Бухоро шаҳар",
          en: "Bukhara city",
        },
        phoneKod: "0",
        cOrder: "32",
        ns11Code: "1",
        soato: "1706401",
      },
      {
        id: 1037,
        regionId: 103,
        title: {
          latin: "Buxoro tumani",
          cyrl: "Бухоро туман",
          en: "Bukhara district",
        },
        phoneKod: "0",
        cOrder: "33",
        ns11Code: "5",
        soato: "1706207",
      },
      {
        id: 1039,
        regionId: 103,
        title: {
          latin: "Vobkent tumani",
          cyrl: "Вобкент туман",
          en: "Vobkent district",
        },
        phoneKod: "0",
        cOrder: "34",
        ns11Code: "6",
        soato: "1706212",
      },
      {
        id: 1040,
        regionId: 103,
        title: {
          latin: "G‘ijduvon tumani",
          cyrl: "Ғиждувон туман",
          en: "Gijduvan district",
        },
        phoneKod: "0",
        cOrder: "35",
        ns11Code: "7",
        soato: "1706215",
      },
      {
        id: 1042,
        regionId: 103,
        title: {
          latin: "Jondor tumani",
          cyrl: "Жондор туман",
          en: "Jondor District",
        },
        phoneKod: "0",
        cOrder: "36",
        ns11Code: "8",
        soato: "1706246",
      },
      {
        id: 32,
        regionId: 103,
        title: {
          latin: "Kogon tumani",
          cyrl: "Когон туман",
          en: "Kogon district",
        },
        phoneKod: "0",
        cOrder: "37",
        ns11Code: "9",
        soato: "1706219",
      },
      {
        id: 1046,
        regionId: 103,
        title: {
          latin: "Olot tumani",
          cyrl: "Олот туман",
          en: "Alot district",
        },
        phoneKod: "0",
        cOrder: "38",
        ns11Code: "4",
        soato: "1706204",
      },
      {
        id: 1047,
        regionId: 103,
        title: {
          latin: "Peshku tumani",
          cyrl: "Пешку туман",
          en: "Peshku district",
        },
        phoneKod: "0",
        cOrder: "39",
        ns11Code: "11",
        soato: "1706240",
      },
      {
        id: 1048,
        regionId: 103,
        title: {
          latin: "Romitan tumani",
          cyrl: "Ромитан туман",
          en: "Romitan district",
        },
        phoneKod: "0",
        cOrder: "40",
        ns11Code: "12",
        soato: "1706242",
      },
      {
        id: 1049,
        regionId: 103,
        title: {
          latin: "Shofirkon tumani",
          cyrl: "Шофиркон туман",
          en: "Shofirkon district",
        },
        phoneKod: "0",
        cOrder: "41",
        ns11Code: "13",
        soato: "1706258",
      },
      {
        id: 1044,
        regionId: 103,
        title: {
          latin: "Qorako‘l tumani",
          cyrl: "Қоракўл туман",
          en: "Karakul district",
        },
        phoneKod: "0",
        cOrder: "42",
        ns11Code: "10",
        soato: "1706230",
      },
      {
        id: 1045,
        regionId: 103,
        title: {
          latin: "Qorovulbozor tumani",
          cyrl: "Қоровулбозор туман",
          en: "Qorovulbozor district",
        },
        phoneKod: "0",
        cOrder: "43",
        ns11Code: "14",
        soato: "1706232",
      },
      {
        id: 1042,
        regionId: 103,
        title: { latin: "Kogon shahar", cyrl: "Когон шаҳар", en: "Kogon city" },
        phoneKod: "0",
        cOrder: "44",
        ns11Code: "3",
        soato: "1706403",
      },
    ],
  },
  {
    id: 107,
    title: "Samarqand viloyati",
    "hc-key": "uz-sa",
    districts: [
      {
        id: 1103,
        regionId: 107,
        title: {
          latin: "Tayloq tumani",
          cyrl: "Тайлоқ тумани",
          en: "Tayloq district",
        },
        phoneKod: "0",
        cOrder: "110",
        ns11Code: "23",
        soato: "1718239",
      },
      {
        id: 1100,
        regionId: 107,
        title: {
          latin: "Samarqand shahar",
          cyrl: "Самарқанд шаҳар",
          en: "Samarqand city",
        },
        phoneKod: "0",
        cOrder: "94",
        ns11Code: "1",
        soato: "1718401",
      },
      {
        id: 1095,
        regionId: 107,
        title: {
          latin: "Oqdaryo tumani",
          cyrl: "Оқдарё тумани",
          en: "Oqdaryo district",
        },
        phoneKod: "0",
        cOrder: "95",
        ns11Code: "8",
        soato: "1718203",
      },
      {
        id: 1087,
        regionId: 107,
        title: {
          latin: "Bulung‘ur tumani",
          cyrl: "Булунғур тумани",
          en: "Bulungur district",
        },
        phoneKod: "0",
        cOrder: "96",
        ns11Code: "9",
        soato: "1718206",
      },
      {
        id: 1088,
        regionId: 107,
        title: {
          latin: "Jomboy tumani",
          cyrl: "Жомбой тумани",
          en: "Jomboy district",
        },
        phoneKod: "0",
        cOrder: "97",
        ns11Code: "11",
        soato: "1718209",
      },
      {
        id: 1090,
        regionId: 107,
        title: {
          latin: "Kattaqo‘rg‘on tumani",
          cyrl: "Каттақўрғон тумани",
          en: "Kattakurgan district",
        },
        phoneKod: "0",
        cOrder: "98",
        ns11Code: "14",
        soato: "1718215",
      },
      {
        id: 1091,
        regionId: 107,
        title: {
          latin: "Kattaqo‘rg‘on shahar",
          cyrl: "Каттақўрғон шаҳар",
          en: "Kattakurgan city",
        },
        phoneKod: "0",
        cOrder: "99",
        ns11Code: "6",
        soato: "1718406",
      },
      {
        id: 1092,
        regionId: 107,
        title: {
          latin: "Qo‘shrabot tumani",
          cyrl: "Қўшрабод тумани",
          en: "Koshrabad district",
        },
        phoneKod: "0",
        cOrder: "100",
        ns11Code: "14",
        soato: "1718216",
      },
      {
        id: 1093,
        regionId: 107,
        title: {
          latin: "Narpay tumani",
          cyrl: "Нарпай тумани",
          en: "Narpay district",
        },
        phoneKod: "0",
        cOrder: "101",
        ns11Code: "15",
        soato: "1718218",
      },
      {
        id: 1094,
        regionId: 107,
        title: {
          latin: "Nurobod tumani",
          cyrl: "Нуробод тумани",
          en: "Nurobod district",
        },
        phoneKod: "0",
        cOrder: "102",
        ns11Code: "21",
        soato: "1718235",
      },
      {
        id: 1096,
        regionId: 107,
        title: {
          latin: "Payariq tumani",
          cyrl: "Пайариқ тумани",
          en: "Payariq district",
        },
        phoneKod: "0",
        cOrder: "103",
        ns11Code: "17",
        soato: "1718224",
      },
      {
        id: 1097,
        regionId: 107,
        title: {
          latin: "Pastdarg‘om tumani",
          cyrl: "Пастдарғом тумани",
          en: "Pastdargom district",
        },
        phoneKod: "0",
        cOrder: "104",
        ns11Code: "18",
        soato: "1718227",
      },
      {
        id: 1098,
        regionId: 107,
        title: {
          latin: "Paxtachi tumani",
          cyrl: "Пахтачи тумани",
          en: "Pakhtachi district",
        },
        phoneKod: "0",
        cOrder: "105",
        ns11Code: "19",
        soato: "1718230",
      },
      {
        id: 1099,
        regionId: 107,
        title: {
          latin: "Samarqand tumani",
          cyrl: "Самарқанд тумани",
          en: "Samarkand district",
        },
        phoneKod: "0",
        cOrder: "106",
        ns11Code: "20",
        soato: "1718233",
      },
      {
        id: 1102,
        regionId: 107,
        title: {
          latin: "Urgut tumani",
          cyrl: "Ургут тумани",
          en: "Urgut district",
        },
        phoneKod: "0",
        cOrder: "108",
        ns11Code: "22",
        soato: "1718236",
      },
      {
        id: 1089,
        regionId: 107,
        title: {
          latin: "Ishtixon tumani",
          cyrl: "Иштихон тумани",
          en: "Ishtixon district",
        },
        phoneKod: "0",
        cOrder: "109",
        ns11Code: "12",
        soato: "1718212",
      },
    ],
  },
  {
    id: 105,
    title: "Navoiy viloyati",
    "hc-key": "uz-nw",
    districts: [
      {
        id: 1070,
        regionId: 105,
        title: {
          latin: "Navoiy shahar",
          cyrl: "Навоий шаҳар",
          en: "Navoi city",
        },
        phoneKod: "0",
        cOrder: "72",
        ns11Code: "1",
        soato: "1712401",
      },
      {
        id: 1066,
        regionId: 105,
        title: {
          latin: "Karmana tumani",
          cyrl: "Кармана тумани",
          en: "Karmana district",
        },
        phoneKod: "0",
        cOrder: "73",
        ns11Code: "11",
        soato: "1712234",
      },
      {
        id: 1069,
        regionId: 105,
        title: {
          latin: "Navbahor tumani",
          cyrl: "Навбахор тумани",
          en: "Navbahor district",
        },
        phoneKod: "0",
        cOrder: "74",
        ns11Code: "8",
        soato: "1712230",
      },
      {
        id: 1064,
        regionId: 4,
        title: {
          latin: "G‘ozg‘on shahar",
          cyrl: "Гўзгон шаҳар",
          en: "G‘ozg‘on city",
        },
        phoneKod: "0",
        cOrder: "49",
        ns11Code: "4",
        soato: "1708210",
      },
      {
        id: 1071,
        regionId: 105,
        title: {
          latin: "Nurota tumani",
          cyrl: "Нурота тумани",
          en: "Nurata district",
        },
        phoneKod: "0",
        cOrder: "75",
        ns11Code: "10",
        soato: "1712238",
      },
      {
        id: 1074,
        regionId: 105,
        title: {
          latin: "Xatirchi tumani",
          cyrl: "Хатирчи тумани",
          en: "Hatirchi district",
        },
        phoneKod: "0",
        cOrder: "76",
        ns11Code: "9",
        soato: "1712251",
      },
      {
        id: 1068,
        regionId: 105,
        title: {
          latin: "Qiziltepa tumani",
          cyrl: "Қизилтепа тумани",
          en: "Qiziltepa district",
        },
        phoneKod: "0",
        cOrder: "77",
        ns11Code: "5",
        soato: "1712216",
      },
      {
        id: 1067,
        regionId: 105,
        title: {
          latin: "Konimex tumani",
          cyrl: "Конимех тумани",
          en: "Konimex district",
        },
        phoneKod: "0",
        cOrder: "78",
        ns11Code: "4",
        soato: "1712211",
      },
      {
        id: 1073,
        regionId: 105,
        title: {
          latin: "Uchquduq tumani",
          cyrl: "Учқудуқ тумани",
          en: "Uchkuduk district",
        },
        phoneKod: "0",
        cOrder: "79",
        ns11Code: "3",
        soato: "1712248",
      },
      {
        id: 1065,
        regionId: 105,
        title: {
          latin: "Zarafshon shahar",
          cyrl: "Зарафшон шаҳар",
          en: "Zafarobod district",
        },
        phoneKod: "0",
        cOrder: "80",
        ns11Code: "2",
        soato: "1712408",
      },
      {
        id: 1072,
        regionId: 105,
        title: {
          latin: "Tomdi tumani",
          cyrl: "Томди тумани",
          en: "Tomdi district",
        },
        phoneKod: "0",
        cOrder: "81",
        ns11Code: "2019",
        soato: "1712244",
      },
    ],
  },
  {
    id: 102,
    title: "Andijon viloyati",
    "hc-key": "uz-an",
    districts: [
      {
        id: 1025,
        regionId: 102,
        title: {
          latin: "Bo‘ston tumani",
          cyrl: "Бўстон тумани",
          en: "Bo‘ston district",
        },
        phoneKod: "0",
        cOrder: "142",
        ns11Code: "4",
        soato: "1705212",
      },
      {
        id: 1019,
        regionId: 102,
        title: {
          latin: "Andijon shahar",
          cyrl: "Андижон шаҳар",
          en: "Andijan city",
        },
        phoneKod: "0",
        cOrder: "16",
        ns11Code: "1",
        soato: "1703401",
      },
      {
        id: 1034,
        regionId: 102,
        title: {
          latin: "Xonobod shahar",
          cyrl: "Хонобод шаҳар",
          en: "Hanabad city",
        },
        phoneKod: "0",
        cOrder: "17",
        ns11Code: "3",
        soato: "1703408",
      },
      {
        id: 1018,
        regionId: 102,
        title: {
          latin: "Andijon tumani",
          cyrl: "Андижон тумани",
          en: "Andijan district",
        },
        phoneKod: "0",
        cOrder: "18",
        ns11Code: "7",
        soato: "1703203",
      },
      {
        id: 1020,
        regionId: 102,
        title: {
          latin: "Asaka tumani",
          cyrl: "Асака тумани",
          en: "Asaka district",
        },
        phoneKod: "0",
        cOrder: "19",
        ns11Code: "15",
        soato: "1703224",
      },
      {
        id: 1022,
        regionId: 102,
        title: {
          latin: "Baliqchi tumani",
          cyrl: "Балиқчи тумани",
          en: "Baliqchi district",
        },
        phoneKod: "0",
        cOrder: "20",
        ns11Code: "8",
        soato: "1703206",
      },
      {
        id: 1728,
        regionId: 102,
        title: { latin: "Bo'z tumani", cyrl: "Бўз тумани", en: "Boz district" },
        phoneKod: "0",
        cOrder: "21",
        ns11Code: "9",
        soato: "1703209",
      },
      {
        id: 1024,
        regionId: 102,
        title: {
          latin: "Buloqboshi tumani",
          cyrl: "Булоқбоши тумани",
          en: "Buloqboshi district",
        },
        phoneKod: "0",
        cOrder: "22",
        ns11Code: "10",
        soato: "1703210",
      },
      {
        id: 1026,
        regionId: 102,
        title: {
          latin: "Jalaquduq tumani",
          cyrl: "Жалолқудуқ тумани",
          en: "Jalalkuduk district",
        },
        phoneKod: "0",
        cOrder: "23",
        ns11Code: "11",
        soato: "1703211",
      },
      {
        id: 1027,
        regionId: 102,
        title: {
          latin: "Izboskan tumani",
          cyrl: "Избоскан тумани",
          en: "Izboskan district",
        },
        phoneKod: "0",
        cOrder: "24",
        ns11Code: "12",
        soato: "1703214",
      },
      {
        id: 1035,
        regionId: 102,
        title: {
          latin: "Xo‘jaobod tumani",
          cyrl: "Хўжаобод тумани",
          en: "Khojaobod district",
        },
        phoneKod: "0",
        cOrder: "25",
        ns11Code: "13",
        soato: "1703215",
      },
      {
        id: 1033,
        regionId: 102,
        title: {
          latin: "Ulug‘nor tumani",
          cyrl: "Улуғнор тумани",
          en: "Ulugnor district",
        },
        phoneKod: "0",
        cOrder: "25",
        ns11Code: "13",
        soato: "1703217",
      },
      {
        id: 1029,
        regionId: 102,
        title: {
          latin: "Qo‘rg‘ontepa tumani",
          cyrl: "Қўрғонтепа тумани",
          en: "Kurgantepa district",
        },
        phoneKod: "0",
        cOrder: "26",
        ns11Code: "14",
        soato: "1703220",
      },
      {
        id: 1030,
        regionId: 102,
        title: {
          latin: "Marxamat tumani",
          cyrl: "Мархамат тумани",
          en: "Marhamat district",
        },
        phoneKod: "0",
        cOrder: "27",
        ns11Code: "16",
        soato: "1703227",
      },
      {
        id: 1031,
        regionId: 102,
        title: {
          latin: "Oltinko‘l tumani",
          cyrl: "Олтинкўл тумани",
          en: "Oltinkol district",
        },
        phoneKod: "0",
        cOrder: "28",
        ns11Code: "6",
        soato: "1703202",
      },
      {
        id: 1032,
        regionId: 102,
        title: {
          latin: "Paxtaobod tumani",
          cyrl: "Пахтаобод тумани",
          en: "Pakhtaobod district",
        },
        phoneKod: "0",
        cOrder: "29",
        ns11Code: "18",
        soato: "1703232",
      },
      {
        id: 1035,
        regionId: 102,
        title: {
          latin: "Ho'jaobod tumani",
          cyrl: "Ҳўжаобод тумани",
          en: "Hodjaabad district",
        },
        phoneKod: "0",
        cOrder: "30",
        ns11Code: "19",
        soato: "1703236",
      },
      {
        id: 1036,
        regionId: 102,
        title: {
          latin: "Shaxrixon tumani",
          cyrl: "Шахрихон тумани",
          en: "Shahrihan district",
        },
        phoneKod: "0",
        cOrder: "31",
        ns11Code: "17",
        soato: "1703230",
      },
    ],
  },
  {
    id: 112,
    title: "Farg‘ona viloyati",
    "hc-key": "uz-fa",
    districts: [
      {
        id: 1172,
        regionId: 112,
        title: {
          latin: "Marg‘ilon shahar",
          cyrl: "Марғилон шаҳар",
          en: "Margilan city",
        },
        phoneKod: "0",
        cOrder: "153",
        ns11Code: "4",
        soato: "1730412",
      },
      {
        id: 1182,
        regionId: 112,
        title: {
          latin: "Farg‘ona shahar",
          cyrl: "Фарғона шаҳар",
          en: "Fergana city",
        },
        phoneKod: "0",
        cOrder: "154",
        ns11Code: "5",
        soato: "1730401",
      },
      {
        id: 1169,
        regionId: 112,
        title: {
          latin: "Quvasoy shahar",
          cyrl: "Қувасой шаҳар",
          en: "Quvasay city",
        },
        phoneKod: "0",
        cOrder: "155",
        ns11Code: "1",
        soato: "1730408",
      },
      {
        id: 1170,
        regionId: 112,
        title: {
          latin: "Qo‘qon shahar",
          cyrl: "Қўқон шаҳар",
          en: "Kokand city",
        },
        phoneKod: "0",
        cOrder: "156",
        ns11Code: "3",
        soato: "1730405",
      },
      {
        id: 1164,
        regionId: 112,
        title: {
          latin: "Bog‘dod tumani",
          cyrl: "Боғдод тумани",
          en: "Bagdad district",
        },
        phoneKod: "0",
        cOrder: "157",
        ns11Code: "7",
        soato: "1730209",
      },
      {
        id: 1163,
        regionId: 112,
        title: {
          latin: "Beshariq tumani",
          cyrl: "Бешариқ тумани",
          en: "Beshariq district",
        },
        phoneKod: "0",
        cOrder: "158",
        ns11Code: "6",
        soato: "1730215",
      },
      {
        id: 1165,
        regionId: 112,
        title: {
          latin: "Buvayda tumani",
          cyrl: "Бувайда тумани",
          en: "Buvayda District",
        },
        phoneKod: "0",
        cOrder: "159",
        ns11Code: "8",
        soato: "1730212",
      },
      {
        id: 1166,
        regionId: 112,
        title: {
          latin: "Dang‘ara tumani",
          cyrl: "Данғара тумани",
          en: "Dangara district",
        },
        phoneKod: "0",
        cOrder: "160",
        ns11Code: "9",
        soato: "1730236",
      },
      {
        id: 1167,
        regionId: 112,
        title: {
          latin: "Yozyovon tumani",
          cyrl: "Ёзёвон тумани",
          en: "Yozyovon district",
        },
        phoneKod: "0",
        cOrder: "161",
        ns11Code: "10",
        soato: "1730242",
      },
      {
        id: 1173,
        regionId: 112,
        title: {
          latin: "Oltiariq tumani",
          cyrl: "Олтиариқ тумани",
          en: "Oltiaryk district",
        },
        phoneKod: "0",
        cOrder: "162",
        ns11Code: "12",
        soato: "1730203",
      },
      {
        id: 1171,
        regionId: 112,
        title: {
          latin: "Qo‘shtepa tumani",
          cyrl: "Қўштепа тумани",
          en: "Kushtepa district",
        },
        phoneKod: "0",
        cOrder: "163",
        ns11Code: "13",
        soato: "1730206",
      },
      {
        id: 1175,
        regionId: 112,
        title: {
          latin: "Rishton tumani",
          cyrl: "Риштон тумани",
          en: "Rishtan district",
        },
        phoneKod: "0",
        cOrder: "164",
        ns11Code: "14",
        soato: "1730224",
      },
      {
        id: 1177,
        regionId: 112,
        title: {
          latin: "So‘x tumani",
          cyrl: "Сўх тумани",
          en: "Sokh district",
        },
        phoneKod: "0",
        cOrder: "165",
        ns11Code: "5",
        soato: "1730226",
      },
      {
        id: 1178,
        regionId: 112,
        title: {
          latin: "Toshloq tumani",
          cyrl: "Тошлоқ тумани",
          en: "Tashlaq district",
        },
        phoneKod: "0",
        cOrder: "166",
        ns11Code: "16",
        soato: "1730227",
      },
      {
        id: 1180,
        regionId: 112,
        title: {
          latin: "Uchko‘prik tumani",
          cyrl: "Учкўприк тумани",
          en: "Uchkuprik district",
        },
        phoneKod: "0",
        cOrder: "167",
        ns11Code: "18",
        soato: "1730221",
      },
      {
        id: 1181,
        regionId: 112,
        title: {
          latin: "Farg‘ona tumani",
          cyrl: "Фарғона тумани",
          en: "Fergana district",
        },
        phoneKod: "0",
        cOrder: "168",
        ns11Code: "19",
        soato: "1730233",
      },
      {
        id: 1183,
        regionId: 112,
        title: {
          latin: "Furqat tumani",
          cyrl: "Фурқат тумани",
          en: "Furqat district",
        },
        phoneKod: "0",
        cOrder: "169",
        ns11Code: "20",
        soato: "1730238",
      },
      {
        id: 1179,
        regionId: 112,
        title: {
          latin: "O‘zbekiston tumani",
          cyrl: "Ўзбекистон тумани",
          en: "Uzbekistan district",
        },
        phoneKod: "0",
        cOrder: "170",
        ns11Code: "17",
        soato: "1730230",
      },
      {
        id: 1168,
        regionId: 112,
        title: {
          latin: "Quva tumani",
          cyrl: "Қува тумани",
          en: "Kuva district",
        },
        phoneKod: "0",
        cOrder: "171",
        ns11Code: "11",
        soato: "1730218",
      },
    ],
  },
  {
    id: 109,
    title: "Surxondaryo viloyati",
    "hc-key": "uz-su",
    districts: [
      {
        id: 1114,
        regionId: 109,
        title: {
          latin: "Angor tumani",
          cyrl: "Ангор тумани",
          en: "Angor district",
        },
        phoneKod: "0",
        cOrder: "121",
        ns11Code: "3",
        soato: "1722202",
      },
      {
        id: 1116,
        regionId: 109,
        title: {
          latin: "Boysun tumani",
          cyrl: "Бойсун тумани",
          en: "Boysun district",
        },
        phoneKod: "0",
        cOrder: "122",
        ns11Code: "5",
        soato: "1722204",
      },
      {
        id: 1117,
        regionId: 109,
        title: {
          latin: "Denov tumani",
          cyrl: "Денов тумани",
          en: "Denau district",
        },
        phoneKod: "0",
        cOrder: "123",
        ns11Code: "7",
        soato: "1722210",
      },
      {
        id: 1118,
        regionId: 109,
        title: {
          latin: "Jarqo‘rg‘on tumani",
          cyrl: "Жарқўрғон тумани",
          en: "Jarkurgan district",
        },
        phoneKod: "0",
        cOrder: "124",
        ns11Code: "8",
        soato: "1722212",
      },
      {
        id: 1119,
        regionId: 109,
        title: {
          latin: "Qiziriq tumani",
          cyrl: "Қизириқ тумани",
          en: "Qiziriq district",
        },
        phoneKod: "0",
        cOrder: "125",
        ns11Code: "10",
        soato: "1722215",
      },
      {
        id: 1120,
        regionId: 109,
        title: {
          latin: "Qumqo‘rg‘on tumani",
          cyrl: "Қумқўрғон тумани",
          en: "Kumkurgan district",
        },
        phoneKod: "0",
        cOrder: "126",
        ns11Code: "9",
        soato: "1722214",
      },
      {
        id: 1121,
        regionId: 109,
        title: {
          latin: "Muzrabot tumani",
          cyrl: "Музработ тумани",
          en: "Muzrabot district",
        },
        phoneKod: "0",
        cOrder: "127",
        ns11Code: "6",
        soato: "1722207",
      },
      {
        id: 1122,
        regionId: 109,
        title: {
          latin: "Oltinsoy tumani",
          cyrl: "Олтинсой тумани",
          en: "Oltinsoy district",
        },
        phoneKod: "0",
        cOrder: "128",
        ns11Code: "4",
        soato: "1722201",
      },
      {
        id: 1123,
        regionId: 109,
        title: {
          latin: "Sariosiyo tumani",
          cyrl: "Сариосиё тумани",
          en: "Sariosiyo district",
        },
        phoneKod: "0",
        cOrder: "129",
        ns11Code: "11",
        soato: "1722217",
      },
      {
        id: 1124,
        regionId: 109,
        title: {
          latin: "Termiz tumani",
          cyrl: "Термиз тумани",
          en: "Termez district",
        },
        phoneKod: "0",
        cOrder: "130",
        ns11Code: "12",
        soato: "1722220",
      },
      {
        id: 1115,
        regionId: 7,
        title: {
          latin: "Bandixon tumani",
          cyrl: "Бандихон тумани",
          en: "Bandixon district",
        },
        phoneKod: "0",
        cOrder: "135",
        ns11Code: "15",
        soato: "1710110",
      },
      {
        id: 1125,
        regionId: 109,
        title: { latin: "Termiz", cyrl: "Термиз шаҳар", en: "Termiz city" },
        phoneKod: "0",
        cOrder: "131",
        ns11Code: "1",
        soato: "1722401",
      },
      {
        id: 1126,
        regionId: 109,
        title: {
          latin: "Uzun tumani",
          cyrl: "Узун тумани",
          en: "Uzun district",
        },
        phoneKod: "0",
        cOrder: "132",
        ns11Code: "15",
        soato: "1722221",
      },
      {
        id: 1127,
        regionId: 109,
        title: {
          latin: "Sherobod tumani",
          cyrl: "Шеробод тумани",
          en: "Sherobod district",
        },
        phoneKod: "0",
        cOrder: "133",
        ns11Code: "13",
        soato: "1722223",
      },
      {
        id: 1128,
        regionId: 109,
        title: {
          latin: "Sho‘rchi tumani",
          cyrl: "Шўрчи тумани",
          en: "Shurchi district",
        },
        phoneKod: "0",
        cOrder: "134",
        ns11Code: "14",
        soato: "1722226",
      },
    ],
  },
  {
    id: 108,
    title: "Sirdaryo viloyati",
    "hc-key": "uz-si",
    districts: [
      {
        id: 1107,
        regionId: 108,
        title: {
          latin: "Oqoltin tumani",
          cyrl: "Оқолтин тумани",
          en: "Akaltyn district",
        },
        phoneKod: "0",
        cOrder: "110",
        ns11Code: "1",
        soato: "1724206",
      },
      {
        id: 1103,
        regionId: 108,
        title: {
          latin: "Boyovut tumani",
          cyrl: "Боёвут тумани",
          en: "Boyovut district",
        },
        phoneKod: "0",
        cOrder: "111",
        ns11Code: "2",
        soato: "1724212",
      },
      {
        id: 1104,
        regionId: 108,
        title: {
          latin: "Guliston tumani",
          cyrl: "Гулистон тумани",
          en: "Guliston district",
        },
        phoneKod: "0",
        cOrder: "112",
        ns11Code: "3",
        soato: "1724220",
      },
      {
        id: 1106,
        regionId: 108,
        title: {
          latin: "Mirzaobod tumani",
          cyrl: "Мирзаобод тумани",
          en: "Mirzaobod district",
        },
        phoneKod: "0",
        cOrder: "113",
        ns11Code: "5",
        soato: "1724228",
      },
      {
        id: 1108,
        regionId: 108,
        title: {
          latin: "Sayxunobod tumani",
          cyrl: "Сайхунобод тумани",
          en: "Saykhunobod district",
        },
        phoneKod: "0",
        cOrder: "114",
        ns11Code: "6",
        soato: "1724216",
      },
      {
        id: 1110,
        regionId: 108,
        title: {
          latin: "Sirdaryo tumani",
          cyrl: "Сирдарё тумани",
          en: "Sirdarya district",
        },
        phoneKod: "0",
        cOrder: "115",
        ns11Code: "7",
        soato: "1724231",
      },
      {
        id: 1109,
        regionId: 108,
        title: {
          latin: "Sardoba tumani",
          cyrl: "Сардоба тумани",
          en: "Sardoba district",
        },
        phoneKod: "0",
        cOrder: "116",
        ns11Code: "9",
        soato: "1724226",
      },
      {
        id: 1111,
        regionId: 108,
        title: {
          latin: "Xovos tumani",
          cyrl: "Ховос тумани",
          en: "Hawos district",
        },
        phoneKod: "0",
        cOrder: "117",
        ns11Code: "8",
        soato: "1724235",
      },
      {
        id: 1104,
        regionId: 108,
        title: {
          latin: "Guliston shahar",
          cyrl: "Гулистон шаҳар",
          en: "Gulistan city",
        },
        phoneKod: "0",
        cOrder: "118",
        ns11Code: "10",
        soato: "1724401",
      },
      {
        id: 1112,
        regionId: 108,
        title: {
          latin: "Shirin shahar",
          cyrl: "Ширин шаҳар",
          en: "shirin district",
        },
        phoneKod: "0",
        cOrder: "119",
        ns11Code: "2019",
        soato: "1724410",
      },
      {
        id: 1113,
        regionId: 108,
        title: {
          latin: "Yangiyer shahar",
          cyrl: "Янгиер шаҳар",
          en: "Yangiyer city",
        },
        phoneKod: "0",
        cOrder: "120",
        ns11Code: "13",
        soato: "1724413",
      },
    ],
  },
  {
    id: 113,
    title: "Xorazm viloyati",
    "hc-key": "uz-kh",
    districts: [
      {
        id: 1190,
        regionId: 113,
        title: { latin: "Urganch", cyrl: "Урганч шаҳар", en: "Urgench city" },
        phoneKod: "0",
        cOrder: "172",
        ns11Code: "1",
        soato: "1733401",
      },
      {
        id: 1188,
        regionId: 113,
        title: {
          latin: "Tuproqqal'a tumani",
          cyrl: "Тупроққалъа тумани",
          en: "Tuprokkala district",
        },
        phoneKod: "0",
        cOrder: "190",
        ns11Code: "14",
        soato: "1733400",
      },
      {
        id: 1184,
        regionId: 113,
        title: {
          latin: "Bog‘ot tumani",
          cyrl: "Боғот тумани",
          en: "Bogot district",
        },
        phoneKod: "0",
        cOrder: "173",
        ns11Code: "11",
        soato: "1733204",
      },
      {
        id: 1185,
        regionId: 113,
        title: {
          latin: "Gurlan tumani",
          cyrl: "Гурлан тумани",
          en: "Gurlan district",
        },
        phoneKod: "0",
        cOrder: "174",
        ns11Code: "7",
        soato: "1733208",
      },
      {
        id: 1191,
        regionId: 113,
        title: {
          latin: "Xazorasp tumani",
          cyrl: "Хозарасп тумани",
          en: "Hazorasp district",
        },
        phoneKod: "0",
        cOrder: "175",
        ns11Code: "6",
        soato: "1733220",
      },
      {
        id: 1192,
        regionId: 113,
        title: {
          latin: "Xiva tumani",
          cyrl: "Хива тумани",
          en: "Khiva district",
        },
        phoneKod: "0",
        cOrder: "176",
        ns11Code: "5",
        soato: "1733226",
      },
      {
        id: 1194,
        regionId: 113,
        title: {
          latin: "Xonqa tumani",
          cyrl: "Хонқа тумани",
          en: "Hanka district",
        },
        phoneKod: "0",
        cOrder: "177",
        ns11Code: "12",
        soato: "1733223",
      },
      {
        id: 1189,
        regionId: 113,
        title: {
          latin: "Urganch tumani",
          cyrl: "Урганч тумани",
          en: "Urgench district",
        },
        phoneKod: "0",
        cOrder: "178",
        ns11Code: "4",
        soato: "1733217",
      },
      {
        id: 1186,
        regionId: 113,
        title: {
          latin: "Qo‘shko‘pir tumani",
          cyrl: "Қўшкўпир тумани",
          en: "Koshkupir district",
        },
        phoneKod: "0",
        cOrder: "179",
        ns11Code: "10",
        soato: "1733212",
      },
      {
        id: 1195,
        regionId: 113,
        title: {
          latin: "Shovot tumani",
          cyrl: "Шовот тумани",
          en: "Shovot district",
        },
        phoneKod: "0",
        cOrder: "180",
        ns11Code: "8",
        soato: "1733230",
      },
      {
        id: 1196,
        regionId: 113,
        title: {
          latin: "Yangiariq tumani",
          cyrl: "Янгиариқ тумани",
          en: "Yangiariq district",
        },
        phoneKod: "0",
        cOrder: "181",
        ns11Code: "9",
        soato: "1733233",
      },
      {
        id: 1197,
        regionId: 113,
        title: {
          latin: "Yangibozor tumani",
          cyrl: "Янгибозор тумани",
          en: "Yangibozor district",
        },
        phoneKod: "0",
        cOrder: "182",
        ns11Code: "13",
        soato: "1733236",
      },
      {
        id: 1193,
        regionId: 113,
        title: { latin: "Xiva", cyrl: "Хива шаҳар", en: "Khiva city" },
        phoneKod: "0",
        cOrder: "183",
        ns11Code: "2",
        soato: "1733406",
      },
      {
        id: 224,
        regionId: 113,
        title: {
          latin: "Pitnak shahar",
          cyrl: "Питнак шаҳар",
          en: "Pitnak city",
        },
        phoneKod: "0",
        cOrder: "2020",
        ns11Code: "3",
        soato: "1733897",
      },
    ],
  },
  {
    id: 110,
    title: "Toshkent viloyati",
    "hc-key": "uz-ta",
    districts: [
      {
        id: 138,
        regionId: 10,
        title: {
          latin: "Angren shahar",
          cyrl: "Ангрен шаҳар",
          en: "Angren city",
        },
        phoneKod: "0",
        cOrder: "135",
        ns11Code: "16",
        soato: "1727407",
      },
      {
        id: 139,
        regionId: 10,
        title: {
          latin: "Bekobod shahar",
          cyrl: "Бекобод шаҳар",
          en: "Bekabad district",
        },
        phoneKod: "0",
        cOrder: "136",
        ns11Code: "17",
        soato: "1727413",
      },
      {
        id: 140,
        regionId: 10,
        title: {
          latin: "Olmaliq shahar",
          cyrl: "Олмалиқ шаҳар",
          en: "Almalik city",
        },
        phoneKod: "0",
        cOrder: "137",
        ns11Code: "18",
        soato: "1727404",
      },
      {
        id: 141,
        regionId: 10,
        title: {
          latin: "Chirchiq shahar",
          cyrl: "Чирчиқ шаҳар",
          en: "Chirchik city",
        },
        phoneKod: "0",
        cOrder: "138",
        ns11Code: "20",
        soato: "1727419",
      },
      {
        id: 142,
        regionId: 10,
        title: {
          latin: "Bekobod tumani",
          cyrl: "Бекобод тумани",
          en: "Bekabad district",
        },
        phoneKod: "0",
        cOrder: "139",
        ns11Code: "1",
        soato: "1727220",
      },
      {
        id: 143,
        regionId: 10,
        title: {
          latin: "Bo‘ka tumani",
          cyrl: "Бўка тумани",
          en: "Boka district",
        },
        phoneKod: "0",
        cOrder: "140",
        ns11Code: "2",
        soato: "1727228",
      },
      {
        id: 145,
        regionId: 10,
        title: {
          latin: "Qibray tumani",
          cyrl: "Қибрай тумани",
          en: "Kibray district",
        },
        phoneKod: "0",
        cOrder: "142",
        ns11Code: "6",
        soato: "1727248",
      },
      {
        id: 146,
        regionId: 10,
        title: {
          latin: "Zangiota tumani",
          cyrl: "Зангиота тумани",
          en: "Zangiota district",
        },
        phoneKod: "0",
        cOrder: "143",
        ns11Code: "4",
        soato: "1727237",
      },
      {
        id: 148,
        regionId: 10,
        title: {
          latin: "Quyichirchiq tumani",
          cyrl: "Қуйичирчиқ тумани",
          en: "Kuyichirchiq district",
        },
        phoneKod: "0",
        cOrder: "144",
        ns11Code: "14",
        soato: "1727233",
      },
      {
        id: 149,
        regionId: 10,
        title: {
          latin: "Oqqo‘rg‘on tumani",
          cyrl: "Оққўрғон тумани",
          en: "Akkurgan district",
        },
        phoneKod: "0",
        cOrder: "145",
        ns11Code: "7",
        soato: "1727206",
      },
      {
        id: 150,
        regionId: 10,
        title: {
          latin: "Ohangaron tumani",
          cyrl: "Охонгарон тумани",
          en: "Oxongary district",
        },
        phoneKod: "0",
        cOrder: "146",
        ns11Code: "8",
        soato: "1727212",
      },
      {
        id: 151,
        regionId: 10,
        title: {
          latin: "Parkent tumani",
          cyrl: "Паркент тумани",
          en: "Parkent district",
        },
        phoneKod: "0",
        cOrder: "147",
        ns11Code: "9",
        soato: "1727249",
      },
      {
        id: 152,
        regionId: 10,
        title: {
          latin: "Piskent tumani",
          cyrl: "Пскент тумани",
          en: "Pskent district",
        },
        phoneKod: "0",
        cOrder: "148",
        ns11Code: "10",
        soato: "1727250",
      },
      {
        id: 153,
        regionId: 10,
        title: {
          latin: "O‘rtachirchiq tumani",
          cyrl: "Ўртачирчиқ тумани",
          en: "Urtachirchik district",
        },
        phoneKod: "0",
        cOrder: "149",
        ns11Code: "12",
        soato: "1727253",
      },
      {
        id: 154,
        regionId: 10,
        title: {
          latin: "Chinoz tumani",
          cyrl: "Чиноз тумани",
          en: "Chinaz district",
        },
        phoneKod: "0",
        cOrder: "150",
        ns11Code: "13",
        soato: "1727256",
      },
      {
        id: 155,
        regionId: 10,
        title: {
          latin: "Yuqorichirchiq tumani",
          cyrl: "Юқоричирчиқ тумани",
          en: "Yukori Chirchiq district",
        },
        phoneKod: "0",
        cOrder: "151",
        ns11Code: "5",
        soato: "1727239",
      },
      {
        id: 156,
        regionId: 10,
        title: {
          latin: "Yangiyo‘l tumani",
          cyrl: "Янгийўл тумани",
          en: "Yangiyol district",
        },
        phoneKod: "0",
        cOrder: "152",
        ns11Code: "15",
        soato: "1727259",
      },
      {
        id: 220,
        regionId: 10,
        title: {
          latin: "Toshkent tumani",
          cyrl: "Тошкент тумани",
          en: "Тошкент тумани",
        },
        phoneKod: "0",
        cOrder: "2019",
        ns11Code: "2019",
        soato: "1727265",
      },
      {
        id: 221,
        regionId: 10,
        title: {
          latin: "Yangiyo'l shahar",
          cyrl: "Янгийўл шаҳар",
          en: "Янгийўл шаҳар",
        },
        phoneKod: "0",
        cOrder: "2019",
        ns11Code: "2019",
        soato: "1727424",
      },
      {
        id: 125,
        regionId: 10,
        title: {
          latin: "Bo‘stonliq tumani",
          cyrl: "Бўстонлиқ тумани",
          en: "Bostanliq district",
        },
        phoneKod: "71",
        cOrder: "160",
        ns11Code: "11",
        soato: "1710300",
      },
      {
        id: 222,
        regionId: 10,
        title: {
          latin: "Ohangaron shahar",
          cyrl: "Оҳангарон шаҳар",
          en: "Оҳангарон шаҳар",
        },
        phoneKod: "0",
        cOrder: "2019",
        ns11Code: "19",
        soato: "1727415",
      },
      {
        id: 223,
        regionId: 10,
        title: {
          latin: "Nurafshon shahar",
          cyrl: "Нурафшон шаҳар",
          en: "Нурафшон шаҳар",
        },
        phoneKod: "0",
        cOrder: "2019",
        ns11Code: "2019",
        soato: "1727401",
      },
    ],
  },
  {
    id: 114,
    title: "Qashqadaryo viloyati",
    "hc-key": "uz-qa",
    districts: [
      {
        id: 158,
        regionId: 11,
        title: {
          latin: "Qarshi shahar",
          cyrl: "Қарши шаҳар",
          en: "Karshi city",
        },
        phoneKod: "0",
        cOrder: "58",
        ns11Code: "1",
        soato: "1710401",
      },
      {
        id: 159,
        regionId: 11,
        title: {
          latin: "G‘uzor tumani",
          cyrl: "Ғузор тумани",
          en: "Guzar district",
        },
        phoneKod: "0",
        cOrder: "59",
        ns11Code: "4",
        soato: "1710207",
      },
      {
        id: 160,
        regionId: 11,
        title: {
          latin: "Qarshi tumani",
          cyrl: "Қарши тумани",
          en: "Karshi district",
        },
        phoneKod: "0",
        cOrder: "60",
        ns11Code: "7",
        soato: "1710224",
      },
      {
        id: 161,
        regionId: 11,
        title: {
          latin: "Kasbi tumani",
          cyrl: "Касби тумани",
          en: "Kasbi district",
        },
        phoneKod: "0",
        cOrder: "61",
        ns11Code: "12",
        soato: "1710237",
      },
      {
        id: 162,
        regionId: 11,
        title: {
          latin: "Koson tumani",
          cyrl: "Косон тумани",
          en: "Koson district",
        },
        phoneKod: "0",
        cOrder: "62",
        ns11Code: "8",
        soato: "1710229",
      },
      {
        id: 163,
        regionId: 11,
        title: {
          latin: "Kitob tumani",
          cyrl: "Китоб тумани",
          en: "Kitob district",
        },
        phoneKod: "0",
        cOrder: "63",
        ns11Code: "9",
        soato: "1710232",
      },
      {
        id: 164,
        regionId: 11,
        title: {
          latin: "Mirishkor tumani",
          cyrl: "Миришкор тумани",
          en: "Mirishkor district",
        },
        phoneKod: "0",
        cOrder: "64",
        ns11Code: "17",
        soato: "1710233",
      },
      {
        id: 165,
        regionId: 11,
        title: {
          latin: "Muborak tumani",
          cyrl: "Муборак тумани",
          en: "Mubarak district",
        },
        phoneKod: "0",
        cOrder: "65",
        ns11Code: "10",
        soato: "1710234",
      },
      {
        id: 166,
        regionId: 11,
        title: {
          latin: "Nishon tumani",
          cyrl: "Нишон тумани",
          en: "Nishan district",
        },
        phoneKod: "0",
        cOrder: "66",
        ns11Code: "11",
        soato: "1710235",
      },
      {
        id: 167,
        regionId: 11,
        title: {
          latin: "Chiroqchi tumani",
          cyrl: "Чироқчи тумани",
          en: "Chirakchi district",
        },
        phoneKod: "0",
        cOrder: "67",
        ns11Code: "14",
        soato: "1710242",
      },
      {
        id: 168,
        regionId: 11,
        title: {
          latin: "Shahrisabz tumani",
          cyrl: "Шахрисабз тумани",
          en: "Shakhrisabz district",
        },
        phoneKod: "0",
        cOrder: "68",
        ns11Code: "15",
        soato: "1710245",
      },
      {
        id: 219,
        regionId: 11,
        title: {
          latin: "Shahrisabz shahar",
          cyrl: "Шахрисабз шаҳар",
          en: "Shakhrisabz city",
        },
        phoneKod: "0",
        cOrder: "2019",
        ns11Code: "2",
        soato: "1710405",
      },
      {
        id: 173,
        regionId: 11,
        title: {
          latin: "Ko'kdala tumani",
          cyrl: "Кўкдала тумани",
          en: "Kokdala district",
        },
        phoneKod: "0",
        cOrder: "72",
        ns11Code: "18",
        soato: "1710255",
      },
      {
        id: 170,
        regionId: 11,
        title: {
          latin: "Qamashi tumani",
          cyrl: "Қамаши тумани",
          en: "Kamashi district",
        },
        phoneKod: "0",
        cOrder: "69",
        ns11Code: "6",
        soato: "1710220",
      },
      {
        id: 171,
        regionId: 11,
        title: {
          latin: "Dehqonobod tumani",
          cyrl: "Дехқонобод тумани",
          en: "Dehqonobod district",
        },
        phoneKod: "0",
        cOrder: "70",
        ns11Code: "5",
        soato: "1710212",
      },
      {
        id: 172,
        regionId: 11,
        title: {
          latin: "Yakkabog‘ tumani",
          cyrl: "Яккабоғ тумани",
          en: "Yakkabag district",
        },
        phoneKod: "0",
        cOrder: "71",
        ns11Code: "16",
        soato: "1710250",
      },
      {
        id: 219,
        regionId: 11,
        title: {
          latin: "Shaxrisabz shahar",
          cyrl: "Шахрисабз шаҳар",
          en: "Shakhrisabz city",
        },
        phoneKod: "0",
        cOrder: "2019",
        ns11Code: "2",
        soato: "1710405",
      },
    ],
  },
  {
    id: 104,
    title: "Jizzax viloyati",
    "hc-key": "uz-ji",
    districts: [
      {
        id: 173,
        regionId: 12,
        title: {
          latin: "Jizzax shahar",
          cyrl: "Жиззах шаҳар",
          en: "Jizzakh city",
        },
        phoneKod: "0",
        cOrder: "45",
        ns11Code: "12",
        soato: "1708401",
      },
      {
        id: 174,
        regionId: 12,
        title: {
          latin: "Baxmal tumani",
          cyrl: "Бахмал тумани",
          en: "Bakhmal district",
        },
        phoneKod: "0",
        cOrder: "46",
        ns11Code: "2",
        soato: "1708204",
      },
      {
        id: 175,
        regionId: 12,
        title: {
          latin: "Do‘stlik tumani",
          cyrl: "Дўстлик тумани",
          en: "Dustlik district",
        },
        phoneKod: "0",
        cOrder: "47",
        ns11Code: "5",
        soato: "1708215",
      },
      {
        id: 176,
        regionId: 12,
        title: {
          latin: "Sharof Rashidov tumani",
          cyrl: "Шароф Рашидов тумани",
          en: "Sharof Rashidov district",
        },
        phoneKod: "0",
        cOrder: "48",
        ns11Code: "3",
        soato: "1708209",
      },
      {
        id: 176,
        regionId: 12,
        title: {
          latin: "G‘allaorol tumani",
          cyrl: "Ғаллаорол тумани",
          en: "Gallaorol district",
        },
        phoneKod: "0",
        cOrder: "48",
        ns11Code: "3",
        soato: "1708209123131232",
      },
      {
        id: 177,
        regionId: 12,
        title: {
          latin: "Jizzax tumani",
          cyrl: "Ш.Рашидов тумани",
          en: "Jizzakh district",
        },
        phoneKod: "0",
        cOrder: "49",
        ns11Code: "4",
        soato: "1708212",
      },
      {
        id: 178,
        regionId: 12,
        title: {
          latin: "Zarbdor tumani",
          cyrl: "Зарбдор тумани",
          en: "Zarbdor district",
        },
        phoneKod: "0",
        cOrder: "50",
        ns11Code: "6",
        soato: "1708220",
      },
      {
        id: 179,
        regionId: 12,
        title: {
          latin: "Zafarobod tumani",
          cyrl: "Зафаробод тумани",
          en: "Zafarobod district",
        },
        phoneKod: "0",
        cOrder: "51",
        ns11Code: "8",
        soato: "1708225",
      },
      {
        id: 180,
        regionId: 12,
        title: {
          latin: "Zomin tumani",
          cyrl: "Зомин тумани",
          en: "Zaamin district",
        },
        phoneKod: "0",
        cOrder: "52",
        ns11Code: "7",
        soato: "1708218",
      },
      {
        id: 181,
        regionId: 12,
        title: {
          latin: "Paxtakor tumani",
          cyrl: "Пахтакор тумани",
          en: "Pakhtakor district",
        },
        phoneKod: "0",
        cOrder: "53",
        ns11Code: "10",
        soato: "1708228",
      },
      {
        id: 182,
        regionId: 12,
        title: {
          latin: "Mirzacho‘l tumani",
          cyrl: "Мирзачўл тумани",
          en: "Mirzachul district",
        },
        phoneKod: "0",
        cOrder: "54",
        ns11Code: "9",
        soato: "1708223",
      },
      {
        id: 183,
        regionId: 12,
        title: {
          latin: "Forish tumani",
          cyrl: "Фориш тумани",
          en: "Forish district",
        },
        phoneKod: "0",
        cOrder: "55",
        ns11Code: "11",
        soato: "1708235",
      },
      {
        id: 184,
        regionId: 12,
        title: {
          latin: "Yangiobod tumani",
          cyrl: "Янгиобод тумани",
          en: "Yangiobod district",
        },
        phoneKod: "0",
        cOrder: "56",
        ns11Code: "13",
        soato: "1708237",
      },
      {
        id: 211,
        regionId: 12,
        title: {
          latin: "Arnasoy tumani",
          cyrl: "Арнасой тумани",
          en: "Arnasay district",
        },
        phoneKod: "0",
        cOrder: "57",
        ns11Code: "1",
        soato: "1708201",
      },
    ],
  },
  {
    id: 106,
    title: "Namangan viloyati",
    "hc-key": "uz-ng",
    districts: [
      {
        id: 185,
        regionId: 13,
        title: {
          latin: "Namangan shahar",
          cyrl: "Наманган шаҳар",
          en: "Namangan city",
        },
        phoneKod: "0",
        cOrder: "82",
        ns11Code: "1",
        soato: "1714401",
      },
      {
        id: 186,
        regionId: 13,
        title: {
          latin: "Mingbuloq tumani",
          cyrl: "Мингбулоқ тумани",
          en: "Mingbulak district",
        },
        phoneKod: "0",
        cOrder: "83",
        ns11Code: "7",
        soato: "1714204",
      },
      {
        id: 189,
        regionId: 13,
        title: { latin: "Pop tumani", cyrl: "Поп тумани", en: "Pop district" },
        phoneKod: "0",
        cOrder: "84",
        ns11Code: "11",
        soato: "1714219",
      },
      {
        id: 190,
        regionId: 13,
        title: {
          latin: "Norin tumani",
          cyrl: "Норин тумани",
          en: "Norin district",
        },
        phoneKod: "0",
        cOrder: "85",
        ns11Code: "10",
        soato: "1714216",
      },
      {
        id: 191,
        regionId: 13,
        title: {
          latin: "To‘raqo‘rg‘on tumani",
          cyrl: "Тўрақўрғон тумани",
          en: "Turakurgan district",
        },
        phoneKod: "0",
        cOrder: "86",
        ns11Code: "12",
        soato: "1714224",
      },
      {
        id: 192,
        regionId: 13,
        title: {
          latin: "Uychi tumani",
          cyrl: "Уйчи тумани",
          en: "Uychi district",
        },
        phoneKod: "0",
        cOrder: "87",
        ns11Code: "13",
        soato: "1714229",
      },
      {
        id: 194,
        regionId: 13,
        title: {
          latin: "Chortoq tumani",
          cyrl: "Чортоқ тумани",
          en: "Chartak district",
        },
        phoneKod: "0",
        cOrder: "88",
        ns11Code: "15",
        soato: "1714236",
      },
      {
        id: 195,
        regionId: 13,
        title: {
          latin: "Chust tumani",
          cyrl: "Чуст тумани",
          en: "Chust district",
        },
        phoneKod: "0",
        cOrder: "89",
        ns11Code: "16",
        soato: "1714237",
      },
      {
        id: 196,
        regionId: 13,
        title: {
          latin: "Yangiqo‘rg‘on tumani",
          cyrl: "Янгиқўрғон тумани",
          en: "Yangikurgan district",
        },
        phoneKod: "0",
        cOrder: "90",
        ns11Code: "17",
        soato: "1714242",
      },
      {
        id: 214,
        regionId: 13,
        title: {
          latin: "Namangan tumani",
          cyrl: "Наманган тумани",
          en: "Namangan district",
        },
        phoneKod: "0",
        cOrder: "91",
        ns11Code: "9",
        soato: "1714212",
      },
      {
        id: 215,
        regionId: 13,
        title: {
          latin: "Uchqo‘rg‘on tumani",
          cyrl: "Учқўрғон тумани",
          en: "Uchkurgan district",
        },
        phoneKod: "0",
        cOrder: "92",
        ns11Code: "14",
        soato: "1714234",
      },
      {
        id: 216,
        regionId: 13,
        title: {
          latin: "Kosonsoy tumani",
          cyrl: "Косонсой тумани",
          en: "Kosonsoy district",
        },
        phoneKod: "0",
        cOrder: "93",
        ns11Code: "8",
        soato: "1710207",
      },
    ],
  },
  {
    id: 111,
    title: "Toshkent shahar",
    "hc-key": "uz-tk",
    districts: [
      {
        id: 199,
        regionId: 14,
        title: {
          latin: "Yangihayot tumani",
          cyrl: "Янгихаёт тумани",
          en: "Yangihayot district",
        },
        phoneKod: "0",
        cOrder: "185",
        ns11Code: "4",
        soato: "1726267",
      },
      {
        id: 198,
        regionId: 14,
        title: {
          latin: "Yunusobod tumani",
          cyrl: "Юнусобод тумани",
          en: "Yunusobod district",
        },
        phoneKod: "0",
        cOrder: "184",
        ns11Code: "3",
        soato: "1726266",
      },
      {
        id: 199,
        regionId: 14,
        title: {
          latin: "Mirobod tumani",
          cyrl: "Миробод тумани",
          en: "Mirabad district",
        },
        phoneKod: "0",
        cOrder: "185",
        ns11Code: "1",
        soato: "1726273",
      },
      {
        id: 200,
        regionId: 14,
        title: {
          latin: "Yakkasaroy tumani",
          cyrl: "Яккасарой тумани",
          en: "Yakkasaray district",
        },
        phoneKod: "71",
        cOrder: "186",
        ns11Code: "4",
        soato: "1726287",
      },
      {
        id: 201,
        regionId: 14,
        title: {
          latin: "Olmazor tumani",
          cyrl: "Олмазор тумани",
          en: "Olmazor district",
        },
        phoneKod: "0",
        cOrder: "187",
        ns11Code: "9",
        soato: "1726280",
      },
      {
        id: 202,
        regionId: 14,
        title: {
          latin: "Bektemir tumani",
          cyrl: "Бектемир тумани",
          en: "Bektemir district",
        },
        phoneKod: "0",
        cOrder: "188",
        ns11Code: "11",
        soato: "1726264",
      },
      {
        id: 203,
        regionId: 14,
        title: {
          latin: "Yashnobod tumani",
          cyrl: "Яшнобод тумани",
          en: "Yashnobod district",
        },
        phoneKod: "0",
        cOrder: "189",
        ns11Code: "8",
        soato: "1726290",
      },
      {
        id: 204,
        regionId: 14,
        title: {
          latin: "Chilonzor tumani",
          cyrl: "Чилонзор тумани",
          en: "Chilanzar district",
        },
        phoneKod: "0",
        cOrder: "190",
        ns11Code: "6",
        soato: "1726294",
      },
      {
        id: 205,
        regionId: 14,
        title: {
          latin: "Uchtepa tumani",
          cyrl: "Учтепа тумани",
          en: "Uchtepa district",
        },
        phoneKod: "0",
        cOrder: "191",
        ns11Code: "10",
        soato: "1726262",
      },
      {
        id: 207,
        regionId: 14,
        title: {
          latin: "Mirzo Ulug'bek tumani",
          cyrl: "Мирзо Улуғбек тумани",
          en: "Mirzo Ulugbek district",
        },
        phoneKod: "0",
        cOrder: "192",
        ns11Code: "2",
        soato: "1726269",
      },
      {
        id: 208,
        regionId: 14,
        title: {
          latin: "Sirg'ali tumani",
          cyrl: "Сирғали тумани",
          en: "Sirg'ali district",
        },
        phoneKod: "0",
        cOrder: "193",
        ns11Code: "7",
        soato: "1726283",
      },
      {
        id: 212,
        regionId: 14,
        title: {
          latin: "Shayxontoxur tumani",
          cyrl: "Шайхонтохур тумани",
          en: "Shaykhantakhur district",
        },
        phoneKod: "0",
        cOrder: "194",
        ns11Code: "5",
        soato: "1726277",
      },
    ],
  },
];
