CREATE TABLE regions (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  isdeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  isdeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  role_id SMALLINT REFERENCES role(id),
  region_id SMALLINT REFERENCES regions(id),
  fio VARCHAR(200),
  login VARCHAR(200),
  password VARCHAR(200),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  isdeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE access (
  id SERIAL PRIMARY KEY,
  role_create BOOLEAN DEFAULT FALSE,
  role_update BOOLEAN DEFAULT FALSE,
  role_get BOOLEAN DEFAULT FALSE,
  role_delete BOOLEAN DEFAULT FALSE,
  region_create BOOLEAN DEFAULT FALSE,
  region_update BOOLEAN DEFAULT FALSE,
  region_get BOOLEAN DEFAULT FALSE,
  region_delete BOOLEAN DEFAULT FALSE,
  users_create BOOLEAN DEFAULT FALSE,
  users_update BOOLEAN DEFAULT FALSE,
  users_get BOOLEAN DEFAULT FALSE,
  users_delete BOOLEAN DEFAULT FALSE,
  budjet_create BOOLEAN DEFAULT FALSE,
  budjet_update BOOLEAN DEFAULT FALSE,
  budjet_get BOOLEAN DEFAULT FALSE,
  budjet_delete BOOLEAN DEFAULT FALSE,
  access_update BOOLEAN DEFAULT FALSE,
  access_get BOOLEAN DEFAULT FALSE,
  main_schet_create BOOLEAN DEFAULT FALSE,
  main_schet_update BOOLEAN DEFAULT FALSE,
  main_schet_get BOOLEAN DEFAULT FALSE,
  main_schet_delete BOOLEAN DEFAULT FALSE,
  operatsii_create BOOLEAN DEFAULT FALSE,
  operatsii_update BOOLEAN DEFAULT FALSE,
  operatsii_get BOOLEAN DEFAULT FALSE,
  operatsii_delete BOOLEAN DEFAULT FALSE,
  organization_create BOOLEAN DEFAULT FALSE,
  organization_update BOOLEAN DEFAULT FALSE,
  organization_get BOOLEAN DEFAULT FALSE,
  organization_delete BOOLEAN DEFAULT FALSE,
  podotchet_create BOOLEAN DEFAULT FALSE,
  podotchet_update BOOLEAN DEFAULT FALSE,
  podotchet_get BOOLEAN DEFAULT FALSE,
  podotchet_delete BOOLEAN DEFAULT FALSE,
  podpis_create BOOLEAN DEFAULT FALSE,
  podpis_update BOOLEAN DEFAULT FALSE,
  podpis_get BOOLEAN DEFAULT FALSE,
  podpis_delete BOOLEAN DEFAULT FALSE,
  podrazdelenie_create BOOLEAN DEFAULT FALSE,
  podrazdelenie_update BOOLEAN DEFAULT FALSE,
  podrazdelenie_get BOOLEAN DEFAULT FALSE,
  podrazdelenie_delete BOOLEAN DEFAULT FALSE,
  sostav_create BOOLEAN DEFAULT FALSE,
  sostav_update BOOLEAN DEFAULT FALSE,
  sostav_get BOOLEAN DEFAULT FALSE,
  sostav_delete BOOLEAN DEFAULT FALSE,
  type_operatsii_create BOOLEAN DEFAULT FALSE,
  type_operatsii_update BOOLEAN DEFAULT FALSE,
  type_operatsii_get BOOLEAN DEFAULT FALSE,
  type_operatsii_delete BOOLEAN DEFAULT FALSE,
  akt_create BOOLEAN DEFAULT FALSE,
  akt_update BOOLEAN DEFAULT FALSE,
  akt_get BOOLEAN DEFAULT FALSE,
  akt_delete BOOLEAN DEFAULT FALSE,
  admin_create BOOLEAN DEFAULT FALSE,
  admin_update BOOLEAN DEFAULT FALSE,
  admin_get BOOLEAN DEFAULT FALSE,
  admin_delete BOOLEAN DEFAULT FALSE,
  avans_create BOOLEAN DEFAULT FALSE,
  avans_update BOOLEAN DEFAULT FALSE,
  avans_get BOOLEAN DEFAULT FALSE,
  avans_delete BOOLEAN DEFAULT FALSE,
  bank_prixod_create BOOLEAN DEFAULT FALSE,
  bank_prixod_update BOOLEAN DEFAULT FALSE,
  bank_prixod_get BOOLEAN DEFAULT FALSE,
  bank_prixod_delete BOOLEAN DEFAULT FALSE,
  bank_rasxod_create BOOLEAN DEFAULT FALSE,
  bank_rasxod_update BOOLEAN DEFAULT FALSE,
  bank_rasxod_get BOOLEAN DEFAULT FALSE,
  bank_rasxod_delete BOOLEAN DEFAULT FALSE,
  bank_monitoring BOOLEAN DEFAULT FALSE,
  internal_j7_create BOOLEAN DEFAULT FALSE,
  internal_j7_update BOOLEAN DEFAULT FALSE,
  internal_j7_get BOOLEAN DEFAULT FALSE,
  internal_j7_delete BOOLEAN DEFAULT FALSE,
  prixod_j7_create BOOLEAN DEFAULT FALSE,
  prixod_j7_update BOOLEAN DEFAULT FALSE,
  prixod_j7_get BOOLEAN DEFAULT FALSE,
  prixod_j7_delete BOOLEAN DEFAULT FALSE,
  rasxod_j7_create BOOLEAN DEFAULT FALSE,
  rasxod_j7_update BOOLEAN DEFAULT FALSE,
  rasxod_j7_get BOOLEAN DEFAULT FALSE,
  rasxod_j7_delete BOOLEAN DEFAULT FALSE,
  iznos_j7 BOOLEAN DEFAULT FALSE,
  group_j7_create BOOLEAN DEFAULT FALSE,
  group_j7_update BOOLEAN DEFAULT FALSE,
  group_j7_get BOOLEAN DEFAULT FALSE,
  group_j7_delete BOOLEAN DEFAULT FALSE,
  product_j7_create BOOLEAN DEFAULT FALSE,
  product_j7_update BOOLEAN DEFAULT FALSE,
  product_j7_get BOOLEAN DEFAULT FALSE,
  product_j7_delete BOOLEAN DEFAULT FALSE,
  pereotsenka_j7_create BOOLEAN DEFAULT FALSE,
  pereotsenka_j7_update BOOLEAN DEFAULT FALSE,
  pereotsenka_j7_get BOOLEAN DEFAULT FALSE,
  pereotsenka_j7_delete BOOLEAN DEFAULT FALSE,
  podrazdelenie_j7_create BOOLEAN DEFAULT FALSE,
  podrazdelenie_j7_update BOOLEAN DEFAULT FALSE,
  podrazdelenie_j7_get BOOLEAN DEFAULT FALSE,
  podrazdelenie_j7_delete BOOLEAN DEFAULT FALSE,
  responsible_j7_create BOOLEAN DEFAULT FALSE,
  responsible_j7_update BOOLEAN DEFAULT FALSE,
  responsible_j7_get BOOLEAN DEFAULT FALSE,
  responsible_j7_delete BOOLEAN DEFAULT FALSE,
  unit_storage_j7_create BOOLEAN DEFAULT FALSE,
  unit_storage_j7_update BOOLEAN DEFAULT FALSE,
  unit_storage_j7_get BOOLEAN DEFAULT FALSE,
  unit_storage_j7_delete BOOLEAN DEFAULT FALSE,
  kassa_prixod_create BOOLEAN DEFAULT FALSE,
  kassa_prixod_update BOOLEAN DEFAULT FALSE,
  kassa_prixod_get BOOLEAN DEFAULT FALSE,
  kassa_prixod_delete BOOLEAN DEFAULT FALSE,
  kassa_rasxod_create BOOLEAN DEFAULT FALSE,
  kassa_rasxod_update BOOLEAN DEFAULT FALSE,
  kassa_rasxod_get BOOLEAN DEFAULT FALSE,
  kassa_rasxod_delete BOOLEAN DEFAULT FALSE,
  kassa_monitoring BOOLEAN DEFAULT FALSE,
  organ_monitoring BOOLEAN DEFAULT FALSE,
  podotchet_monitoring BOOLEAN DEFAULT FALSE,
  shartnoma_create BOOLEAN DEFAULT FALSE,
  shartnoma_update BOOLEAN DEFAULT FALSE,
  shartnoma_get BOOLEAN DEFAULT FALSE,
  shartnoma_delete BOOLEAN DEFAULT FALSE,
  shartnoma_grafik_create BOOLEAN DEFAULT FALSE,
  shartnoma_grafik_update BOOLEAN DEFAULT FALSE,
  shartnoma_grafik_get BOOLEAN DEFAULT FALSE,
  shartnoma_grafik_delete BOOLEAN DEFAULT FALSE,
  show_service_create BOOLEAN DEFAULT FALSE,
  show_service_update BOOLEAN DEFAULT FALSE,
  show_service_get BOOLEAN DEFAULT FALSE,
  show_service_delete BOOLEAN DEFAULT FALSE,
  smeta_create BOOLEAN DEFAULT FALSE,
  smeta_update BOOLEAN DEFAULT FALSE,
  smeta_get BOOLEAN DEFAULT FALSE,
  smeta_delete BOOLEAN DEFAULT FALSE,
  smeta_grafik_create BOOLEAN DEFAULT FALSE,
  smeta_grafik_update BOOLEAN DEFAULT FALSE,
  smeta_grafik_get BOOLEAN DEFAULT FALSE,
  smeta_grafik_delete BOOLEAN DEFAULT FALSE,
  role_id INT REFERENCES role(id),
  region_id INT REFERENCES regions(id),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  isdeleted BOOLEAN DEFAULT FALSE
);


CREATE TABLE oldAccess (
  id SERIAL PRIMARY KEY,
  region BOOLEAN DEFAULT FALSE, 
  role BOOLEAN DEFAULT FALSE, 
  role_get BOOLEAN DEFAULT FALSE,
  users BOOLEAN DEFAULT FALSE, 
  budjet_get BOOLEAN DEFAULT FALSE,    
  budjet BOOLEAN DEFAULT FALSE,        
  access BOOLEAN DEFAULT FALSE,     
  spravochnik BOOLEAN DEFAULT FALSE, 
  smeta BOOLEAN DEFAULT FALSE, 
  smeta_get BOOLEAN DEFAULT FALSE,     
  smeta_grafik BOOLEAN DEFAULT FALSE,  
  bank BOOLEAN DEFAULT FALSE, 
  kassa BOOLEAN DEFAULT FALSE, 
  shartnoma BOOLEAN DEFAULT FALSE, 
  jur3 BOOLEAN DEFAULT FALSE, 
  jur152 BOOLEAN DEFAULT FALSE,        
  jur4 BOOLEAN DEFAULT FALSE, 
  region_users BOOLEAN DEFAULT FALSE, 
  podotchet_monitoring BOOLEAN DEFAULT FALSE, 
  organization_monitoring BOOLEAN DEFAULT FALSE, 
  jur7 BOOLEAN DEFAULT FALSE, 
  role_id INT REFERENCES role(id),
  region_id INT REFERENCES regions(id),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  isdeleted BOOLEAN DEFAULT FALSE
  );